Repository jps091/for-work, pull requests merged in 2024-09, with the labels that each got.

#32 feat: SalePost, ThumbnailImage 기초 설계
  src/main/java/project/forwork/api/domain/salepost/controller/SalePostController.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostEntity.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostJpaRepository.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostRepositoryImpl.java
  src/main/java/project/forwork/api/domain/salepost/model/SalePost.java
  src/main/java/project/forwork/api/domain/salepost/service/SalePostService.java
  src/main/java/project/forwork/api/domain/salepost/service/port/SalePostRepository.java
  src/main/java/project/forwork/api/domain/thumbnailimage/infrastructure/ThumbnailImageEntity.java
  src/main/java/project/forwork/api/domain/thumbnailimage/model/ThumbnailImage.java
Labels: For: InfraStructure, Type: Feature

#33 sale-resume crud 기능추가
  src/main/java/project/forwork/api/common/error/ResumeErrorCode.java
  src/main/java/project/forwork/api/common/error/SalePostErrorCode.java
  src/main/java/project/forwork/api/domain/order/infrastructure/OrderEntity.java
  src/main/java/project/forwork/api/domain/resume/controller/ResumeController.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/enums/FieldType.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/enums/LevelType.java
  src/main/java/project/forwork/api/domain/resume/model/Resume.java
  src/main/java/project/forwork/api/domain/resume/service/ResumeService.java
  src/main/java/project/forwork/api/domain/salepost/controller/model/SalePostResponse.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostEntity.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostJpaRepository.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostRepositoryImpl.java
  src/main/java/project/forwork/api/domain/salepost/model/SalePost.java
  src/main/java/project/forwork/api/domain/salepost/service/SalePostService.java
  src/main/java/project/forwork/api/domain/salepost/service/SellerValidationService.java
  src/main/java/project/forwork/api/domain/salepost/service/port/SalePostRepository.java
  src/main/java/project/forwork/api/domain/user/controller/model/UserCreateRequest.java
  src/main/java/project/forwork/api/domain/user/controller/model/UserResponse.java
  src/main/java/project/forwork/api/domain/user/infrastructure/UserEntity.java
  src/main/java/project/forwork/api/domain/user/service/UserService.java
Labels: Type: Feature

#39 Feat/cart resume
  src/main/java/project/forwork/api/common/error/CartErrorCode.java
  src/main/java/project/forwork/api/common/error/CartResumeErrorCode.java
  src/main/java/project/forwork/api/common/error/SalePostErrorCode.java
  src/main/java/project/forwork/api/domain/cart/controller/CartController.java
  src/main/java/project/forwork/api/domain/cart/infrastructure/CartEntity.java
  src/main/java/project/forwork/api/domain/cart/infrastructure/CartJpaRepository.java
  src/main/java/project/forwork/api/domain/cart/infrastructure/CartRepositoryImpl.java
  src/main/java/project/forwork/api/domain/cart/infrastructure/enums/CartStatus.java
  src/main/java/project/forwork/api/domain/cart/model/Cart.java
  src/main/java/project/forwork/api/domain/cart/service/CartService.java
  src/main/java/project/forwork/api/domain/cart/service/port/CartRepository.java
  src/main/java/project/forwork/api/domain/cartresume/controller/CartResumeController.java
  src/main/java/project/forwork/api/domain/cartresume/controller/model/CartResumeResponse.java
  src/main/java/project/forwork/api/domain/cartresume/controller/model/CartSummary.java
  src/main/java/project/forwork/api/domain/cartresume/infrastructure/CartResumeEntity.java
  src/main/java/project/forwork/api/domain/cartresume/infrastructure/CartResumeJpaRepository.java
  src/main/java/project/forwork/api/domain/cartresume/infrastructure/CartResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/cartresume/model/CartResume.java
  src/main/java/project/forwork/api/domain/cartresume/service/CartResumeService.java
  src/main/java/project/forwork/api/domain/cartresume/service/port/CartResumeRepository.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostEntity.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/query/SalePostQueryDslRepository.java
  src/main/java/project/forwork/api/domain/salepost/model/SalePost.java
  src/test/java/project/forwork/api/domain/resume/infrastructure/querydsl/ResumeQueryDlsRepositoryTest.java
  src/test/java/project/forwork/api/domain/salepost/infrastructure/query/SalePostQueryDslRepositoryTest.java
  src/test/java/project/forwork/api/mock/FakeSalePostRepository.java
  src/test/resources/sql/resume-test-data.sql
Labels: Type: Feature

#42 feat: Order, OrderResume 구현
  src/main/java/project/forwork/api/common/error/OrderErrorCode.java
  src/main/java/project/forwork/api/domain/cartresume/controller/CartResumeController.java
  src/main/java/project/forwork/api/domain/cartresume/infrastructure/CartResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/cartresume/service/CartResumeService.java
  src/main/java/project/forwork/api/domain/order/controller/OrderController.java
  src/main/java/project/forwork/api/domain/order/controller/model/CancelRequest.java
  src/main/java/project/forwork/api/domain/order/controller/model/OrderRequest.java
  src/main/java/project/forwork/api/domain/order/infrastructure/OrderEntity.java
  src/main/java/project/forwork/api/domain/order/infrastructure/OrderJpaRepository.java
  src/main/java/project/forwork/api/domain/order/infrastructure/OrderRepositoryImpl.java
  src/main/java/project/forwork/api/domain/order/infrastructure/enums/OrderStatus.java
  src/main/java/project/forwork/api/domain/order/model/Order.java
  src/main/java/project/forwork/api/domain/order/service/OrderService.java
  src/main/java/project/forwork/api/domain/order/service/port/OrderRepository.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeEntity.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeJpaRepository.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/enums/OrderResumeStatus.java
  src/main/java/project/forwork/api/domain/orderresume/model/OrderResume.java
  src/main/java/project/forwork/api/domain/orderresume/service/OrderResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/port/OrderResumeRepository.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeEntity.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/resume/model/Resume.java
  src/main/java/project/forwork/api/domain/resume/service/ResumeService.java
  src/main/java/project/forwork/api/domain/user/model/User.java
  src/main/java/project/forwork/api/domain/user/service/UserService.java
Labels: Type: Feature

#43 feat: OrderResumeService 분리, PurchaseInfo 도메인 설계
  src/main/java/project/forwork/api/domain/order/infrastructure/OrderJpaRepository.java
  src/main/java/project/forwork/api/domain/order/service/OrderService.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeJpaRepository.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeQueryDslRepository.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/enums/OrderResumeStatus.java
  src/main/java/project/forwork/api/domain/orderresume/model/PurchaseInfo.java
  src/main/java/project/forwork/api/domain/orderresume/service/OrderResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/port/OrderResumeRepository.java
  src/main/java/project/forwork/api/domain/resume/controller/ResumeAdminController.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeQueryDlsRepository.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeSearchCond.java
  src/main/java/project/forwork/api/domain/resume/service/ResumeService.java
  src/main/java/project/forwork/api/domain/resume/service/port/ResumeRepository.java
  src/main/java/project/forwork/api/domain/salepost/controller/SalePostOpenController.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostQueryDslRepository.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostRepositoryImpl.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostSearchCond.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/enums/SalePostSortType.java
  src/main/java/project/forwork/api/domain/salepost/service/SalePostService.java
  src/main/java/project/forwork/api/domain/salepost/service/port/SalePostRepository.java
  src/test/java/project/forwork/api/domain/resume/infrastructure/querydsl/ResumeQueryDlsRepositoryTest.java
  src/test/java/project/forwork/api/domain/salepost/infrastructure/query/SalePostQueryDslRepositoryTest.java
  src/test/java/project/forwork/api/mock/FakeCartRepository.java
  src/test/java/project/forwork/api/mock/FakeResumeRepository.java
  src/test/java/project/forwork/api/mock/FakeSalePostRepository.java
Labels: Type: Feature

#46 Order, OrderResume Service 테스트 코드 작성
  src/main/java/project/forwork/api/common/error/OrderResumeErrorCode.java
  src/main/java/project/forwork/api/domain/order/controller/model/CancelRequest.java
  src/main/java/project/forwork/api/domain/order/controller/model/OrderRequest.java
  src/main/java/project/forwork/api/domain/order/model/Order.java
  src/main/java/project/forwork/api/domain/order/service/OrderService.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeJpaRepository.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/orderresume/model/OrderResume.java
  src/main/java/project/forwork/api/domain/orderresume/model/PurchaseInfo.java
  src/main/java/project/forwork/api/domain/orderresume/service/OrderResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/port/OrderResumeRepository.java
  src/test/java/project/forwork/api/domain/order/service/OrderServiceTest.java
  src/test/java/project/forwork/api/domain/orderresume/service/OrderResumeServiceTest.java
  src/test/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeServiceTest.java
  src/test/java/project/forwork/api/domain/user/service/PasswordInitializationServiceTest.java
  src/test/java/project/forwork/api/mock/FakeOrderRepository.java
  src/test/java/project/forwork/api/mock/FakeOrderResumeRepository.java
Labels: Type: Test

#47 feat: LoginService 테스트 코드
  src/main/java/project/forwork/api/domain/user/controller/model/UserLoginRequest.java
  src/main/java/project/forwork/api/domain/user/service/LoginService.java
  src/main/java/project/forwork/api/domain/user/service/PasswordInitializationService.java
  src/test/java/project/forwork/api/domain/user/service/LoginServiceTest.java
  src/test/java/project/forwork/api/domain/user/service/PasswordInitializationServiceTest.java
Labels: Type: Test

#51 order-resume 주문 상세보기 & 테스트 코드 작성
  src/main/java/project/forwork/api/domain/order/controller/model/OrderDetailResponse.java
  src/main/java/project/forwork/api/domain/order/infrastructure/OrderJpaRepository.java
  src/main/java/project/forwork/api/domain/order/infrastructure/OrderRepositoryImpl.java
  src/main/java/project/forwork/api/domain/order/infrastructure/enums/OrderStatus.java
  src/main/java/project/forwork/api/domain/order/model/Order.java
  src/main/java/project/forwork/api/domain/order/service/OrderService.java
  src/main/java/project/forwork/api/domain/order/service/port/OrderRepository.java
  src/main/java/project/forwork/api/domain/orderresume/controller/model/OrderResumeResponse.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeJpaRepository.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeQueryDslRepository.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/orderresume/model/PurchaseInfo.java
  src/main/java/project/forwork/api/domain/orderresume/service/OrderResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/port/OrderResumeRepository.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/resume/model/Resume.java
  src/main/java/project/forwork/api/domain/resume/service/ResumeService.java
  src/main/java/project/forwork/api/domain/resume/service/port/ResumeRepository.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostQueryDslRepository.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostRepositoryImpl.java
  src/main/java/project/forwork/api/domain/salepost/service/SalePostService.java
  src/main/java/project/forwork/api/domain/salepost/service/port/SalePostRepository.java
  src/test/java/project/forwork/api/domain/order/service/OrderServiceTest.java
  src/test/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeQueryDslRepositoryTest.java
  src/test/java/project/forwork/api/domain/orderresume/service/OrderResumeServiceTest.java
  src/test/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeServiceTest.java
  src/test/java/project/forwork/api/domain/resume/infrastructure/ResumeQueryDlsRepositoryTest.java
  src/test/java/project/forwork/api/domain/salepost/infrastructure/SalePostQueryDslRepositoryTest.java
  src/test/java/project/forwork/api/mock/FakeOrderRepository.java
  src/test/java/project/forwork/api/mock/FakeOrderResumeRepository.java
  src/test/java/project/forwork/api/mock/FakeResumeRepository.java
  src/test/java/project/forwork/api/mock/FakeSalePostRepository.java
  src/test/resources/sql/delete-all-data.sql
  src/test/resources/sql/order-resume-test-data.sql
  src/test/resources/sql/order-test-data.sql
  src/test/resources/sql/user-test-data.sql
Labels: Type: Feature, Type: Test

#53 refactor: 프로젝트 전체에 불필요한 롬복 어노테이션 제거
  src/main/java/project/forwork/api/common/config/web/WebConfig.java
  src/main/java/project/forwork/api/common/controller/FaviconController.java
  src/main/java/project/forwork/api/domain/cart/infrastructure/CartEntity.java
  src/main/java/project/forwork/api/domain/cart/model/Cart.java
  src/main/java/project/forwork/api/domain/cartresume/controller/model/CartResumeResponse.java
  src/main/java/project/forwork/api/domain/cartresume/controller/model/CartSummary.java
  src/main/java/project/forwork/api/domain/cartresume/infrastructure/CartResumeEntity.java
  src/main/java/project/forwork/api/domain/cartresume/model/CartResume.java
  src/main/java/project/forwork/api/domain/order/controller/model/CancelRequest.java
  src/main/java/project/forwork/api/domain/order/controller/model/OrderRequest.java
  src/main/java/project/forwork/api/domain/order/infrastructure/OrderEntity.java
  src/main/java/project/forwork/api/domain/order/model/Order.java
  src/main/java/project/forwork/api/domain/orderresume/controller/model/PurchaseResponse.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeQueryDslRepository.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/port/OrderResumeRepository.java
  src/main/java/project/forwork/api/domain/resume/controller/model/ResumeDetailResponse.java
  src/main/java/project/forwork/api/domain/resume/controller/model/ResumeModifyRequest.java
  src/main/java/project/forwork/api/domain/resume/controller/model/ResumePage.java
  src/main/java/project/forwork/api/domain/resume/controller/model/ResumeRegisterRequest.java
  src/main/java/project/forwork/api/domain/resume/controller/model/ResumeResponse.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeSearchCond.java
  src/main/java/project/forwork/api/domain/resumedecision/controller/model/ResumeDecisionResponse.java
  src/main/java/project/forwork/api/domain/resumedecision/infrastructure/ResumeDecisionEntity.java
  src/main/java/project/forwork/api/domain/resumedecision/infrastructure/ResumeDecisionRepositoryImpl.java
  src/main/java/project/forwork/api/domain/resumedecision/model/ResumeDecision.java
  src/main/java/project/forwork/api/domain/resumedecision/service/ResumeDecisionService.java
  src/main/java/project/forwork/api/domain/resumedecision/service/port/ResumeDecisionRepository.java
  src/main/java/project/forwork/api/domain/salepost/controller/model/SalePostPage.java
  src/main/java/project/forwork/api/domain/salepost/controller/model/SalePostResponse.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostEntity.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostSearchCond.java
  src/main/java/project/forwork/api/domain/salepost/model/SalePost.java
  src/main/java/project/forwork/api/domain/user/controller/model/EmailVerifyRequest.java
  src/main/java/project/forwork/api/domain/user/controller/model/ModifyPasswordRequest.java
  src/main/java/project/forwork/api/domain/user/controller/model/UserCreateRequest.java
  src/main/java/project/forwork/api/domain/user/controller/model/UserLoginRequest.java
  src/main/java/project/forwork/api/domain/user/controller/model/UserResponse.java
  src/main/java/project/forwork/api/domain/user/model/User.java
  src/test/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeQueryDslRepositoryTest.java
  src/test/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeServiceTest.java
  src/test/java/project/forwork/api/domain/resume/service/ResumeServiceTest.java
  src/test/java/project/forwork/api/domain/resumedecision/service/ResumeDecisionServiceTest.java
  src/test/java/project/forwork/api/mock/FakeOrderRepository.java
  src/test/java/project/forwork/api/mock/FakeOrderResumeRepository.java
  src/test/java/project/forwork/api/mock/FakeResumeDecisionRepository.java
Labels: Type: Refactor

#55 UserService 테스트 코드 작성 및 판매글 검색 조건 제목제거
  src/main/java/project/forwork/api/common/infrastructure/RedisStringUtilsImpl.java
  src/main/java/project/forwork/api/common/service/port/RedisUtils.java
  src/main/java/project/forwork/api/domain/salepost/controller/SalePostOpenController.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostQueryDslRepository.java
  src/main/java/project/forwork/api/domain/salepost/infrastructure/SalePostSearchCond.java
  src/main/java/project/forwork/api/domain/user/controller/model/EmailVerifyRequest.java
  src/main/java/project/forwork/api/domain/user/controller/model/ModifyPasswordRequest.java
  src/test/java/project/forwork/api/domain/salepost/infrastructure/SalePostQueryDslRepositoryTest.java
  src/test/java/project/forwork/api/domain/user/service/UserServiceTest.java
  src/test/java/project/forwork/api/mock/FakeMailSender.java
  src/test/java/project/forwork/api/mock/FakeRedisUtils.java
Labels: Type: Test

#56 feat: health-check 를 위한 actuator 설정
  build.gradle
  src/main/java/project/forwork/api/common/config/web/WebConfig.java
Labels: Type: Feature

#71 h2 인모메리 미연결 해결, QueryDsl Repository 추상화
  src/main/java/project/forwork/ForworkApplication.java
  src/main/java/project/forwork/api/domain/order/service/OrderService.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeRepositoryCustomImpl.java
  src/main/java/project/forwork/api/domain/orderresume/service/OrderResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/port/OrderResumeRepositoryCustom.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeJpaRepository.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeRepositoryCustomImpl.java
  src/main/java/project/forwork/api/domain/resume/service/ResumeService.java
  src/main/java/project/forwork/api/domain/resume/service/port/ResumeRepositoryCustom.java
  src/main/java/project/forwork/api/domain/salespost/infrastructure/SalesPostRepositoryCustomImpl.java
  src/main/java/project/forwork/api/domain/salespost/infrastructure/SalesPostRepositoryImpl.java
  src/main/java/project/forwork/api/domain/salespost/service/SalesPostService.java
  src/main/java/project/forwork/api/domain/salespost/service/port/SalesPostRepository.java
  src/main/java/project/forwork/api/domain/salespost/service/port/SalesPostRepositoryCustom.java
  src/test/java/project/forwork/api/config/TestConfig.java
  src/test/java/project/forwork/api/domain/cartresume/service/CartResumeServiceTest.java
  src/test/java/project/forwork/api/domain/order/service/OrderServiceTest.java
  src/test/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeQueryDslRepositoryTest.java
  src/test/java/project/forwork/api/domain/orderresume/service/OrderResumeServiceTest.java
  src/test/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeServiceTest.java
  src/test/java/project/forwork/api/domain/resume/infrastructure/ResumeRepositoryCustomImplTest.java
  src/test/java/project/forwork/api/domain/resume/service/ResumeServiceTest.java
  src/test/java/project/forwork/api/domain/resumedecision/service/ResumeDecisionServiceTest.java
  src/test/java/project/forwork/api/domain/salepost/infrastructure/SalesPostRepositoryCustomImplTest.java
  src/test/java/project/forwork/api/domain/salepost/service/SellerValidationServiceTest.java
  src/test/java/project/forwork/api/mock/FakeResumeRepository.java
  src/test/java/project/forwork/api/mock/FakeSalesPostRepository.java
  src/test/resources/schema.sql
Labels: Type: Errors/Bugs, Type: Refactor, Type: Test

#74 order-resume 메일서비스 수정, cart-resume 선택기능 및 전체선택, 삭제
  src/main/java/project/forwork/api/common/error/CartResumeErrorCode.java
  src/main/java/project/forwork/api/common/error/OrderErrorCode.java
  src/main/java/project/forwork/api/domain/cart/infrastructure/CartEntity.java
  src/main/java/project/forwork/api/domain/cart/model/Cart.java
  src/main/java/project/forwork/api/domain/cartresume/controller/CartResumeController.java
  src/main/java/project/forwork/api/domain/cartresume/controller/model/CartResumeDetailResponse.java
  src/main/java/project/forwork/api/domain/cartresume/controller/model/CartResumeResponse.java
  src/main/java/project/forwork/api/domain/cartresume/infrastructure/CartResumeJpaRepository.java
  src/main/java/project/forwork/api/domain/cartresume/infrastructure/CartResumeRepositoryImpl.java
  src/main/java/project/forwork/api/domain/cartresume/service/CartResumeService.java
  src/main/java/project/forwork/api/domain/cartresume/service/port/CartResumeRepository.java
  src/main/java/project/forwork/api/domain/order/controller/OrderController.java
  src/main/java/project/forwork/api/domain/order/controller/model/OrderCreateResponse.java
  src/main/java/project/forwork/api/domain/order/controller/model/OrderResponse.java
  src/main/java/project/forwork/api/domain/order/infrastructure/OrderJpaRepository.java
  src/main/java/project/forwork/api/domain/order/infrastructure/OrderRepositoryImpl.java
  src/main/java/project/forwork/api/domain/order/model/Order.java
  src/main/java/project/forwork/api/domain/order/service/OrderService.java
  src/main/java/project/forwork/api/domain/order/service/port/OrderRepository.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeJpaRepository.java
  src/main/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeRepositoryCustomImpl.java
  src/main/java/project/forwork/api/domain/orderresume/service/OrderResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeService.java
  src/main/java/project/forwork/api/domain/orderresume/service/port/OrderResumeRepositoryCustom.java
  src/test/java/project/forwork/api/domain/cartresume/service/CartResumeServiceTest.java
  src/test/java/project/forwork/api/domain/order/service/OrderServiceTest.java
  src/test/java/project/forwork/api/domain/orderresume/infrastructure/OrderResumeQueryDslRepositoryTest.java
  src/test/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeServiceTest.java
  src/test/java/project/forwork/api/mock/FakeCartResumeRepository.java
  src/test/java/project/forwork/api/mock/FakeOrderRepository.java
  src/test/resources/sql/order-resume-test-data.sql
Labels: Type: Refactor

#76 feat: 인증 헤더 형태로 JWT 토큰 관리 기능
  src/main/java/project/forwork/api/common/config/swageer/SwaggerConfig.java
  src/main/java/project/forwork/api/common/infrastructure/MailSenderImpl.java
  src/main/java/project/forwork/api/domain/cart/controller/CartController.java
  src/main/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeService.java
  src/main/java/project/forwork/api/domain/token/controller/TokenCookiesController.java
  src/main/java/project/forwork/api/domain/token/service/TokenHeaderService.java
  src/main/java/project/forwork/api/domain/token/service/TokenService.java
  src/main/java/project/forwork/api/domain/user/controller/UserOpenApiController.java
  src/main/java/project/forwork/api/domain/user/controller/model/LoginResponse.java
  src/main/java/project/forwork/api/domain/user/service/LoginService.java
  src/main/java/project/forwork/api/domain/user/service/UserService.java
  src/main/java/project/forwork/api/interceptor/AuthorizationInterceptor.java
  src/test/java/project/forwork/api/domain/user/service/LoginServiceTest.java
  src/test/java/project/forwork/api/domain/user/service/UserServiceTest.java
Labels: Type: Feature

#80 페이징 처리 api 1개로 통합
  src/main/java/project/forwork/api/common/infrastructure/enums/FieldType.java
  src/main/java/project/forwork/api/common/infrastructure/enums/LevelType.java
  src/main/java/project/forwork/api/domain/cart/controller/CartController.java
  src/main/java/project/forwork/api/domain/cart/infrastructure/CartEntity.java
  src/main/java/project/forwork/api/domain/cart/model/Cart.java
  src/main/java/project/forwork/api/domain/cart/service/CartService.java
  src/main/java/project/forwork/api/domain/orderresume/controller/model/OrderResumeResponse.java
  src/main/java/project/forwork/api/domain/orderresume/controller/model/PurchaseResponse.java
  src/main/java/project/forwork/api/domain/resume/controller/ResumeAdminController.java
  src/main/java/project/forwork/api/domain/resume/controller/model/ResumeDetailResponse.java
  src/main/java/project/forwork/api/domain/resume/controller/model/ResumeModifyRequest.java
  src/main/java/project/forwork/api/domain/resume/controller/model/ResumeRegisterRequest.java
  src/main/java/project/forwork/api/domain/resume/controller/model/ResumeResponse.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeEntity.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeRepositoryCustomImpl.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeSearchCond.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/ResumeSearchCond2.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/enums/PageStep.java
  src/main/java/project/forwork/api/domain/resume/infrastructure/enums/PeriodCond.java
  src/main/java/project/forwork/api/domain/resume/model/Resume.java
  src/main/java/project/forwork/api/domain/resume/service/ResumeService.java
  src/main/java/project/forwork/api/domain/resume/service/port/ResumeRepositoryCustom.java
  src/main/java/project/forwork/api/domain/resumedecision/controller/model/ResumeDecisionResponse.java
  src/main/java/project/forwork/api/domain/salespost/controller/SalesPostOpenController.java
  src/main/java/project/forwork/api/domain/salespost/controller/model/SalesPostDetailResponse.java
  src/main/java/project/forwork/api/domain/salespost/controller/model/SalesPostFilterCond.java
  src/main/java/project/forwork/api/domain/salespost/controller/model/SalesPostResponse.java
  src/main/java/project/forwork/api/domain/salespost/controller/model/SalesPostSellerResponse.java
  src/main/java/project/forwork/api/domain/salespost/infrastructure/SalesPostRepositoryCustomImpl.java
  src/main/java/project/forwork/api/domain/salespost/infrastructure/SalesPostSearchCond.java
  src/main/java/project/forwork/api/domain/salespost/infrastructure/enums/FieldCond.java
  src/main/java/project/forwork/api/domain/salespost/infrastructure/enums/LevelCond.java
  src/main/java/project/forwork/api/domain/salespost/infrastructure/enums/SalesPostSortType.java
  src/main/java/project/forwork/api/domain/salespost/service/SalesPostService.java
  src/main/java/project/forwork/api/domain/salespost/service/port/SalesPostRepositoryCustom.java
  src/main/java/project/forwork/api/domain/thumbnailimage/infrastructure/ThumbnailImageEntity.java
  src/main/java/project/forwork/api/domain/thumbnailimage/model/ThumbnailImage.java
  src/main/java/project/forwork/api/domain/user/service/UserService.java
  src/test/java/project/forwork/api/domain/cartresume/service/CartResumeServiceTest.java
  src/test/java/project/forwork/api/domain/order/service/OrderServiceTest.java
  src/test/java/project/forwork/api/domain/orderresume/service/OrderResumeServiceTest.java
  src/test/java/project/forwork/api/domain/orderresume/service/SendPurchaseResumeServiceTest.java
  src/test/java/project/forwork/api/domain/resume/infrastructure/ResumeRepositoryCustomImplTest.java
  src/test/java/project/forwork/api/domain/resume/service/ResumeServiceTest.java
  src/test/java/project/forwork/api/domain/resumedecision/service/ResumeDecisionServiceTest.java
  src/test/java/project/forwork/api/domain/salepost/infrastructure/SalesPostRepositoryCustomImplTest.java
  src/test/java/project/forwork/api/domain/salepost/service/SalesPostServiceTest.java
  src/test/java/project/forwork/api/domain/salepost/service/SellerValidationServiceTest.java
  src/test/java/project/forwork/api/domain/user/service/UserServiceTest.java
  src/test/java/project/forwork/api/mock/FakeCartRepository.java
Labels: Type: Refactor
